name: beptroly_frontend
description: BepTroLy mobile app skeleton
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  dio: ^4.0.0
  web_socket_channel: ^2.2.0
  intl: ^0.18.0
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
